# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: '[Blog] Next.js Bundle Analysis'

on:
  pull_request:
    paths:
      - 'web/**'  
  push:
    branches:
      - main
      - next
    paths:
      - 'web/**'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./web

jobs:
  analyze_blog:
    name: "[Blog] Next.js Bundle Analysis"
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
      cancel-in-progress: true
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: signalco
      TURBO_REMOTE_ONLY: true
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 'latest'
      - uses: actions/setup-node@v3
        with:
            node-version: "18.x"
            cache: "pnpm"
            cache-dependency-path: ./web
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --filter blog... --filter .

      - name: Build next.js Blog
        run: pnpm build --filter=blog

      # Here's the first place where next-bundle-analysis' own script is used
      # This step pulls the raw bundle stats for the current bundle
      - name: Analyze bundle
        run: npx -yes -p github:hashicorp/nextjs-bundle-analysis report
        working-directory: web/apps/blog/

      - name: Upload bundle
        uses: actions/upload-artifact@v3
        with:
          name: bundle
          path: web/apps/blog/.next/analyze/__bundle_analysis.json

      - name: Download base branch bundle stats
        uses: dawidd6/action-download-artifact@v2
        if: success() && github.event.number
        with:
          workflow: blog-nextjs_bundle_analysis.yml
          branch: ${{ github.event.pull_request.base.ref }}
          path: web/apps/blog/.next/analyze/base

      # And here's the second place - this runs after we have both the current and
      # base branch bundle stats, and will compare them to determine what changed.
      # There are two configurable arguments that come from package.json:
      #
      # - budget: optional, set a budget (bytes) against which size changes are measured
      #           it's set to 350kb here by default, as informed by the following piece:
      #           https://infrequently.org/2021/03/the-performance-inequality-gap/
      #
      # - red-status-percentage: sets the percent size increase where you get a red
      #                          status indicator, defaults to 20%
      #
      # Either of these arguments can be changed or removed by editing the `nextBundleAnalysis`
      # entry in your package.json file.
      - name: Compare with base branch bundle
        if: success() && github.event.number
        run: ls -laR .next/analyze/base && npx -yes -p github:hashicorp/nextjs-bundle-analysis compare
        working-directory: web/apps/blog/

      - name: Get comment body
        id: get-comment-body
        if: success() && github.event.number
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const fs = require('fs')
            const comment = fs.readFileSync('web/apps/blog/.next/analyze/__bundle_analysis_comment.txt', 'utf8') + "<!-- __NEXTJS_BUNDLE_BLOG -->"
            core.setOutput('body', comment)

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        if: success() && github.event.number
        id: fc
        with:
          issue-number: ${{ github.event.number }}
          body-includes: '<!-- __NEXTJS_BUNDLE_BLOG -->'

      - name: Create Comment
        uses: peter-evans/create-or-update-comment@v3.0.2
        if: success() && github.event.number && steps.fc.outputs.comment-id == 0
        with:
          issue-number: ${{ github.event.number }}
          body: ${{ steps.get-comment-body.outputs.body }}

      - name: Update Comment
        uses: peter-evans/create-or-update-comment@v3.0.2
        if: success() && github.event.number && steps.fc.outputs.comment-id != 0
        with:
          issue-number: ${{ github.event.number }}
          body: ${{ steps.get-comment-body.outputs.body }}
          comment-id: ${{ steps.fc.outputs.comment-id }}
          edit-mode: replace
