# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: "[Cloud] Deploy"

on:
  push:
    branches: [main, next]
    paths:
      - "cloud/**"
      - "infrastructure/**"
      - ".github/workflows/cloud-deploy.yml"

env:
  DOTNET_VERSION: "7.0.x" # set this to the dotnet version to use

defaults:
  run:
    working-directory: ./cloud/infrastructure

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v3

      - name: ✋ Set up mutex
        uses: ben-z/gh-action-mutex@v1.0-alpha-7
        with:
          branch: mutex/cloud-deploy

      - name: ✨ Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: ✨ Setup Node LTS 
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: yarn
          cache-dependency-path: ./cloud/infrastructure

      - name: 📦️ Installing dependencies 
        run: yarn install

      - name: 🔎 Determine stack
        shell: bash
        run: |
          [[ $(echo ${GITHUB_REF#refs/heads/}) = "main" ]] && echo "##[set-output name=branch;]production" || echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
        env:
          BASE_BRANCH: ${{ github.base_ref }}

      - name: ⚡ Deploy Infrastructure
        uses: pulumi/actions@v4
        with:
          command: up
          stack-name: signalco/cloud-primary/${{ steps.extract_branch.outputs.branch }}
          work-dir: ./cloud/infrastructure
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
