# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: "[Cloud] Preview Deploy"

on:
  pull_request:
    branches:
      - "main"
      - "next"

env:
  DOTNET_VERSION: "6.0.x" # set this to the dotnet version to use

defaults:
  run:
    working-directory: ./cloud/src

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v3

      - name: Set up mutex
        uses: ben-z/gh-action-mutex@v1.0-alpha-7
        with:
          branch: mutex/cloud-preview

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Extract branch name
        shell: bash
        run: |
          [[ $(echo ${BASE_BRANCH#refs/heads/}) = "main" ]] && echo "##[set-output name=branch;]production" || echo "##[set-output name=branch;]$(echo ${BASE_BRANCH#refs/heads/})"
        id: extract_branch
        env:
          BASE_BRANCH: ${{ github.base_ref }}

      - name: Preview infrastructure
        shell: bash
        run: |
          pushd '../infrastructure'
          yarn install
          yarn lint
          pulumi preview --stack signalco/${{ steps.extract_branch.outputs.branch }}
          popd
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
