name: '[Global] Sync `next` Branch'

# This workflow attempts to merge updates from `main` into the long-standing next branch.

on:
  push:
    branches:
      - main
  workflow_dispatch:
concurrency: merge_main

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2
      - name: Merge `main` branch
        uses: everlytic/branch-merge@1.1.5
        id: branch-merge
        with:
          github_token: ${{  secrets.GITHUB_TOKEN }}
          source_ref: 'main'
          target_branch: 'next'
          commit_message_template: '[Automated] Merged {source_ref} into target: {target_branch}'
