# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: '[Global] Sync `next` Branch'

# This workflow attempts to merge updates from `main` into the long-standing next branch.

on:
  push:
    branches:
      - main
  pull_request: 
    branches:
      - main
  workflow_dispatch:

concurrency: merge_main

jobs:
  # When a PR is merged into main, attempt to merge main into next
  sync-next-branch:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        id: cpr
        with:
          destination_branch: 'next'
          pr_title: '[Automated] Merge `main` into target `next`'
          pr_allow_empty: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pr_created == 'true'
        run: gh pr merge --merge --auto "${{ steps.cpr.outputs.pr_number }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # Retarget to next branch if PR is opened against main (and head is not next)
  retarget-feature-prs:
    if: github.event_name == 'pull_request' && github.event.action == 'opened' && github.base_ref == 'main' && github.head_ref != 'next'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4
      - name: Change PR target
        run: gh pr edit ${{ github.event.number }} --base next
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
        
