name: '[Global] Sync `next` Branch'

# This workflow attempts to merge updates from `main` into the long-standing next branch.

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency: merge_main

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        id: cpr
        with:
          title: '[Automated] Merge `main` into target `next`'
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'next'
      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
