name: "stories-check"
on:
  pull_request:
    branches: [next, main]
jobs:
  installDependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2
      - name: Install Dependencies
        uses: actions/setup-node@v2
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
        with:
          args: install
      - name: Run stories-check
        uses: mujo-code/puppeteer-headful@v12
        env:
          CI: "true"
        with:
          args: yarn stories-check
