name: "stories-check"
on:
  pull_request:
    branches: [next, main]
jobs:
  installDependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        uses: actions/setup-node@v2
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
        with:
          node-version: "16.x"
      - run: npm install yarn --global
      - name: Install Yarn
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - run: yarn
      - name: Run stories-check
        uses: mujo-code/puppeteer-headful@v2
        env:
          CI: "true"
        with:
          args: yarn stories-check
