name: "stories-check"
on:
    pull_request:
        branches: [next, main]
jobs:
    check:
        name: Check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: "16.x"
                  cache: "yarn"
            - uses: actions/cache@v3
              with:
                  path: "**/node_modules"
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
            - run: yarn install --network-timeout 1000000
            - name: Run stories-check
              run: yarn stories-check
              id: runStoriesCheck
              continue-on-error: true
            - name: Commit changes
              id: ccc
              if: steps.runStoriesCheck.outcome == 'failure'
              uses: EndBug/add-and-commit@v9
              with:
                  add: ".stories-approved"
                  message: "[skip ci] [stories-check] Automated stories changes"
                  new_branch: ${{ github.head_ref }}
                  default_author: github_actions
              env:
                  GITHUB_TOKEN: ${{ secrets.AT_GH_CD_REPO_PAT }}
