# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: '[Web] Next.js Bundle Analysis'

on:
  pull_request:
    paths:
      - 'web/**'  
  push:
    branches:
      - main
      - next
    paths:
      - 'web/**'
      - '.github/workflows/web-nextjs_bundle_analysis.yml'
      - '.github/workflows/nextjs_bundle_analysis_reusable.yml'
  workflow_dispatch:

jobs:
  analyze_blog:
    name: "[Blog] Next.js Bundle Analysis"
    uses: ./.github/workflows/nextjs_bundle_analysis_reusable.yml
    with:
      workflowName: 'web-nextjs_bundle_analysis.yml'
      name: 'blog'
      path: 'web/apps/blog'
    secrets: inherit
  
  analyze_app:
    name: "[App] Next.js Bundle Analysis"
    uses: ./.github/workflows/nextjs_bundle_analysis_reusable.yml
    with:
      workflowName: 'web-nextjs_bundle_analysis.yml'
      name: 'app'
      path: 'web/apps/app'
    secrets: inherit

  analyze_brandgrab:
    name: "[BrandGrab] Next.js Bundle Analysis"
    uses: ./.github/workflows/nextjs_bundle_analysis_reusable.yml
    with:
      workflowName: 'web-nextjs_bundle_analysis.yml'
      name: 'brandgrab'
      path: 'web/apps/brandgrab'
    secrets: inherit
  
  analyze_web:
    name: "[Web] Next.js Bundle Analysis"
    uses: ./.github/workflows/nextjs_bundle_analysis_reusable.yml
    with:
      workflowName: 'web-nextjs_bundle_analysis.yml'
      name: 'web'
      path: 'web/apps/web'
    secrets: inherit
  
  analyze_slco:
    name: "[slco] Next.js Bundle Analysis"
    uses: ./.github/workflows/nextjs_bundle_analysis_reusable.yml
    with:
      workflowName: 'web-nextjs_bundle_analysis.yml'
      name: 'slco'
      path: 'web/apps/slco'
    secrets: inherit

  analyze_doprocess:
    name: "[doprocess] Next.js Bundle Analysis"
    uses: ./.github/workflows/nextjs_bundle_analysis_reusable.yml
    with:
      workflowName: 'web-nextjs_bundle_analysis.yml'
      name: 'doprocess'
      path: 'web/apps/doprocess.app'
    secrets: inherit