# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: "[Web] Run Tests"
on:
    pull_request:
      paths:
        - "web/**"
        - ".github/workflows/web-test.yml"

defaults:
  run:
    working-directory: ./web

jobs:
    test:
        name: "[Global] Run Tests"
        timeout-minutes: 20
        runs-on: ubuntu-latest
        concurrency:
          group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
          cancel-in-progress: true
        env:
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_TEAM: signalco
          TURBO_REMOTE_ONLY: true
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
          CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
          DOPROCESS_DATABASE_HOST: ${{ secrets.DOPROCESS_DATABASE_HOST }}
          DOPROCESS_DATABASE_USERNAME: ${{ secrets.DOPROCESS_DATABASE_USERNAME }}
          DOPROCESS_DATABASE_PASSWORD: ${{ secrets.DOPROCESS_DATABASE_PASSWORD }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        container:
          image: mcr.microsoft.com/playwright:v1.40.1-focal
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 2
            - name: Setup pnpm
              uses: pnpm/action-setup@v2.4.0
              with:
                version: 'latest'
            - uses: actions/setup-node@v4
              with:
                node-version: "20.x"
                cache: "pnpm"
                cache-dependency-path: ./web
            - name: Install dependencies
              run: pnpm install --frozen-lockfile
            - name: Run tests
              run: pnpm test
